### ISSUE TITLE
TypeScript error in app.tsx

### ISSUE THREAD

**Issue by davidlav** [training4developers/typescript_react_redux_webinar#1]
Great course, really appreciate the minimum working example of these technologies!

However, when trying to run the application today (npm start) I get a TypeScript error on line 8 of app.tsx:

```
Error:(8, 3) TS2322: Type '{ store: Store<AppState>; }' is not assignable to type 'WidgetTableProps'.
  Property 'refreshWidgets' is missing in type '{ store: Store<AppState>; }'.
```

I've tried tracking it down but can't figure it out.  Thanks!

**Comment by ericwgreene** [comment]
I am sorry you are having an issue but this repo is very old. Much has changed with TypeScript, React and Redux in the past couple of years. I would not use this repository as a starting point.

**Comment by davidlav** [comment]
Understood.  Would you mind putting that in the readme however?
